// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyrbJwHyZSAaGfjey-4XzihyzmmB8jjUM',
    appId: '1:46684349136:web:934d040066134ef66834d5',
    messagingSenderId: '46684349136',
    projectId: 'flutter-ecomassignment',
    authDomain: 'flutter-ecomassignment.firebaseapp.com',
    storageBucket: 'flutter-ecomassignment.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZR6SiDR66w15qbjLgz3WFMDxMRiFcJW0',
    appId: '1:46684349136:android:87751ff0790c37826834d5',
    messagingSenderId: '46684349136',
    projectId: 'flutter-ecomassignment',
    storageBucket: 'flutter-ecomassignment.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBG269UEXmyw_o8jYEZcVXtq87hANjoBmM',
    appId: '1:46684349136:ios:c8aa48b464917a2a6834d5',
    messagingSenderId: '46684349136',
    projectId: 'flutter-ecomassignment',
    storageBucket: 'flutter-ecomassignment.appspot.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBG269UEXmyw_o8jYEZcVXtq87hANjoBmM',
    appId: '1:46684349136:ios:c8aa48b464917a2a6834d5',
    messagingSenderId: '46684349136',
    projectId: 'flutter-ecomassignment',
    storageBucket: 'flutter-ecomassignment.appspot.com',
    iosBundleId: 'com.example.ecommerceApp',
  );
}
